-- Trading settings (single row per user — kill switch + mode + guardrails)
create table if not exists public.trading_settings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade unique,
  mode text not null default 'paper' check (mode in ('paper', 'live')),
  autonomous_enabled boolean not null default false,
  kill_switch_engaged boolean not null default true,
  max_position_usd numeric not null default 500,
  max_daily_loss_usd numeric not null default 200,
  min_conviction_score int not null default 8 check (min_conviction_score between 1 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.trading_settings enable row level security;
create policy "ts_select_own" on public.trading_settings for select using (auth.uid() = user_id);
create policy "ts_insert_own" on public.trading_settings for insert with check (auth.uid() = user_id);
create policy "ts_update_own" on public.trading_settings for update using (auth.uid() = user_id);

-- Trade ideas generated by the AI (may or may not become orders)
create table if not exists public.trade_ideas (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  ticker text not null,
  sector text,
  direction text not null check (direction in ('long', 'short')),
  entry_price numeric,
  stop_loss numeric,
  take_profit numeric,
  position_size_usd numeric,
  conviction_score int check (conviction_score between 1 and 10),
  thesis text not null,
  catalysts jsonb,
  risks jsonb,
  sources jsonb,
  status text not null default 'pending' check (status in ('pending', 'executed', 'rejected', 'expired', 'closed')),
  created_at timestamptz not null default now()
);

alter table public.trade_ideas enable row level security;
create policy "ti_select_own" on public.trade_ideas for select using (auth.uid() = user_id);
create policy "ti_insert_own" on public.trade_ideas for insert with check (auth.uid() = user_id);
create policy "ti_update_own" on public.trade_ideas for update using (auth.uid() = user_id);

-- Executed trades (from Alpaca). Used as the feedback loop for the learning system.
create table if not exists public.trades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  idea_id uuid references public.trade_ideas(id) on delete set null,
  broker_order_id text,
  ticker text not null,
  side text not null check (side in ('buy', 'sell')),
  qty numeric not null,
  fill_price numeric,
  status text not null,
  mode text not null check (mode in ('paper', 'live')),
  realized_pnl numeric,
  opened_at timestamptz not null default now(),
  closed_at timestamptz
);

alter table public.trades enable row level security;
create policy "tr_select_own" on public.trades for select using (auth.uid() = user_id);
create policy "tr_insert_own" on public.trades for insert with check (auth.uid() = user_id);
create policy "tr_update_own" on public.trades for update using (auth.uid() = user_id);

-- Learning memory: every decision + eventual outcome. The AI reads recent rows as RAG context.
create table if not exists public.learning_memory (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  ticker text,
  event_type text not null,  -- 'analysis', 'prediction', 'outcome', 'correction'
  summary text not null,
  predicted_direction text,
  predicted_move_pct numeric,
  actual_move_pct numeric,
  was_correct boolean,
  lessons text,
  created_at timestamptz not null default now()
);

alter table public.learning_memory enable row level security;
create policy "lm_select_own" on public.learning_memory for select using (auth.uid() = user_id);
create policy "lm_insert_own" on public.learning_memory for insert with check (auth.uid() = user_id);
create policy "lm_update_own" on public.learning_memory for update using (auth.uid() = user_id);

-- Watchlist
create table if not exists public.watchlist (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  ticker text not null,
  added_at timestamptz not null default now(),
  unique (user_id, ticker)
);

alter table public.watchlist enable row level security;
create policy "wl_select_own" on public.watchlist for select using (auth.uid() = user_id);
create policy "wl_insert_own" on public.watchlist for insert with check (auth.uid() = user_id);
create policy "wl_delete_own" on public.watchlist for delete using (auth.uid() = user_id);

create index if not exists idx_trade_ideas_user_created on public.trade_ideas(user_id, created_at desc);
create index if not exists idx_trades_user_opened on public.trades(user_id, opened_at desc);
create index if not exists idx_learning_user_ticker on public.learning_memory(user_id, ticker, created_at desc);
