-- Personal single-user trading app. No auth dependency.
-- Service role or anon key with permissive access is fine.

-- Trading settings (single row — kill switch + mode + guardrails)
create table if not exists public.trading_settings (
  id int primary key default 1,
  mode text not null default 'paper' check (mode in ('paper', 'live')),
  autonomous_enabled boolean not null default false,
  kill_switch_engaged boolean not null default true,
  max_position_usd numeric not null default 500,
  max_daily_loss_usd numeric not null default 200,
  min_conviction_score int not null default 8 check (min_conviction_score between 1 and 10),
  updated_at timestamptz not null default now(),
  constraint single_row check (id = 1)
);

insert into public.trading_settings (id) values (1)
on conflict (id) do nothing;

-- Trade ideas generated by the AI (may or may not become orders)
create table if not exists public.trade_ideas (
  id uuid primary key default gen_random_uuid(),
  ticker text not null,
  sector text,
  direction text not null check (direction in ('long', 'short')),
  entry_price numeric,
  stop_loss numeric,
  take_profit numeric,
  position_size_usd numeric,
  conviction_score int check (conviction_score between 1 and 10),
  thesis text not null,
  catalysts jsonb,
  risks jsonb,
  sources jsonb,
  status text not null default 'pending' check (status in ('pending', 'executed', 'rejected', 'expired', 'closed')),
  created_at timestamptz not null default now()
);

-- Executed trades (from Alpaca). Feedback loop for the learning system.
create table if not exists public.trades (
  id uuid primary key default gen_random_uuid(),
  idea_id uuid references public.trade_ideas(id) on delete set null,
  broker_order_id text,
  ticker text not null,
  side text not null check (side in ('buy', 'sell')),
  qty numeric not null,
  fill_price numeric,
  status text not null,
  mode text not null check (mode in ('paper', 'live')),
  realized_pnl numeric,
  opened_at timestamptz not null default now(),
  closed_at timestamptz
);

-- Learning memory: every decision + eventual outcome. AI reads recent rows as RAG context.
create table if not exists public.learning_memory (
  id uuid primary key default gen_random_uuid(),
  ticker text,
  event_type text not null,
  summary text not null,
  predicted_direction text,
  predicted_move_pct numeric,
  actual_move_pct numeric,
  was_correct boolean,
  lessons text,
  created_at timestamptz not null default now()
);

-- Watchlist
create table if not exists public.watchlist (
  id uuid primary key default gen_random_uuid(),
  ticker text not null unique,
  added_at timestamptz not null default now()
);

-- Cache for expensive AI analyses (1-hour TTL pattern)
create table if not exists public.analysis_cache (
  cache_key text primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_trade_ideas_created on public.trade_ideas(created_at desc);
create index if not exists idx_trades_opened on public.trades(opened_at desc);
create index if not exists idx_learning_ticker on public.learning_memory(ticker, created_at desc);

-- Permissive RLS (single-user personal app)
alter table public.trading_settings enable row level security;
alter table public.trade_ideas enable row level security;
alter table public.trades enable row level security;
alter table public.learning_memory enable row level security;
alter table public.watchlist enable row level security;
alter table public.analysis_cache enable row level security;

drop policy if exists "allow_all_settings" on public.trading_settings;
drop policy if exists "allow_all_ideas" on public.trade_ideas;
drop policy if exists "allow_all_trades" on public.trades;
drop policy if exists "allow_all_memory" on public.learning_memory;
drop policy if exists "allow_all_watchlist" on public.watchlist;
drop policy if exists "allow_all_cache" on public.analysis_cache;

create policy "allow_all_settings" on public.trading_settings for all using (true) with check (true);
create policy "allow_all_ideas" on public.trade_ideas for all using (true) with check (true);
create policy "allow_all_trades" on public.trades for all using (true) with check (true);
create policy "allow_all_memory" on public.learning_memory for all using (true) with check (true);
create policy "allow_all_watchlist" on public.watchlist for all using (true) with check (true);
create policy "allow_all_cache" on public.analysis_cache for all using (true) with check (true);
